# Generated by Django 3.0.8 on 2020-07-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200718_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='logout_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
