# Generated by Django 3.0.8 on 2020-07-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_userprofile_logout_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='login_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='logout_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
