# Generated by Django 3.0.8 on 2020-07-19 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200719_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='login_time',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='logout_time',
        ),
        migrations.CreateModel(
            name='LogTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('logout_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.UserProfile')),
            ],
            options={
                'ordering': ['user'],
            },
        ),
    ]
